spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/secureauthdb
    username: postgres
    password: Achintya@2026
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080